Add error message for older package is clashing
This tries to resolve #8, but is not yet tested. If the
already-installed version of the Formula is the same version as what is
up-to-date in the remote Tap, then a different message is shown:

    homebrew_automation.rb [info] (2019-10-25T14:22:25+13:00): I've updated the Formula file in our local Tap clone, and we're ready to start building the Bottle. This could take a long time if your Formula is slow to compile.
    ==> Tapping homebrew-automation/tmp-tap
    Cloning into '/usr/local/Homebrew/Library/Taps/homebrew-automation/homebrew-tmp-tap'...
    warning: --depth is ignored in local clones; use file:// instead.
    done.
    Tapped 1 formula (29 files, 86.1KB).
    Updating Homebrew...
    Warning: homebrew-automation/tmp-tap/hack-assembler 0.1.1.28 is already installed and up-to-date
    To reinstall 0.1.1.28, run `brew reinstall hack-assembler`
    ==> Bottling hack-assembler--0.1.1.28.high_sierra.bottle.tar.gz...
    tar cf /Users/eason/pg/hack-assembler/homebrew-tap/hack-assembler--0.1.1.28.high_sierra.bottle.tar hack-assembler/0.1.1.28
    gzip -f hack-assembler-bottle.tar
    ==> Detecting if hack-assembler--0.1.1.28.high_sierra.bottle.tar.gz is relocatable...
    ./hack-assembler--0.1.1.28.high_sierra.bottle.tar.gz
      bottle do
        cellar :any_skip_relocation
        sha256 "9890267aae2a400ceab9a33ff47d5f41dae7dcb9b2b3e2d69a9b82976dc9d63a" => :high_sierra
      end
    homebrew_automation.rb [info] (2019-10-25T14:22:37+13:00): Bottle built! Let me now upload the Bottle tarball to Bintray.

Notice these lines:

    Warning: homebrew-automation/tmp-tap/hack-assembler 0.1.1.28 is already installed and up-to-date
    To reinstall 0.1.1.28, run `brew reinstall hack-assembler`

Compare to what #8 notes (copied here):

    Error: hack-assembler 0.1.1.26 is already installed
    To upgrade to 0.1.1.27, run `brew upgrade hack-assembler`.